---
micronaut:
  application:
    name: micronaut-security

---
micronaut:
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      oauth:
        enabled: true
    token:
      jwt:
        enabled: true
        signatures:
          secret:
            generator:
              secret: 'secretsecret'
#              jwt-algorithm: HS256
---
datasources:
  default:
    url: 'jdbc:h2:mem:usersDB;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE'
    driverClassName: 'org.h2.Driver'
    username: 'sa'
    password: ''

jpa:
  default:
    packages-to-scan:
         - 'edu.micronaut.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true

liquibase:
  datasources:
    default:
      change-log: 'classpath:/db/changelog/db.changelog-master.xml'
